/**
 *  Allows linting and fixing Jest test scripts
 */
module.exports = {
  extends: [
    "./index.js",
    "plugin:jest/recommended",
    "plugin:jest/style"
  ],
  rules: {
    // A few of these rules are auto-fixable. Additionally those that aren't are
    // generally there to promote good maintainable code, and can be disabled
    // individually or for an entire file, and this disabling _should_ be seen
    // as an explicit exception.
    // That said, I have used the "error" level where a specific practice should
    // be heavily discouraged, and "warn" where it should be generally
    // discouraged but there may be situations where it is desired to use jest
    // in this way.

    "jest/consistent-test-it": "error", // Fixable
    // See https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/lowercase-name.md
    // for details on how to provide more exceptions.
    "jest/lowercase-name": [ // Fixable
      "warn",
      {
        ignoreTopLevelDescribe: true,
        allowedPrefixes: [
          "UK", "US", "SE", "BBM", "PCA"
        ],
      }
    ],
    "jest/no-duplicate-hooks": "error",
    "jest/no-if": "error",
    // See https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-large-snapshots.md#options
    // for details on allowing specific snapshots, as an `eslint-disable` cannot
    // be used in snapshots because they are autogenerated. Also, this is only a
    // warning because we almost certainly have a _lot_ of large snapshots.
    // However, it appears that the rule isn't entirely working for me?
    "jest/no-large-snapshots": "warn", // Default is 50 lines which is sensible.
    "jest/no-test-return-statement": "error",
    // This one may get angry on certain code bases (PIO) so should probably be
    // turned off there so the warnings don't lead to missed errors.
    "jest/prefer-called-with": "warn",
    "jest/prefer-hooks-on-top": "error",
    "jest/prefer-todo": "error", // Fixable
    "jest/require-to-throw-message": "warn", // Fixable
  },
}
